require: rubocop-rspec

AllCops:
  Exclude:
    - mini_form.gemspec

  SuggestExtensions: false
  NewCops: disable

# Disables "Module definition is too long"
ModuleLength:
  Enabled: false

# Disables "Line is too long"
LineLength:
  Enabled: false

# Disables "Method is too long"
MethodLength:
  Enabled: false

# Disables "Assignment Branch Condition size for included is too high"
AbcSize:
  Enabled: false

# Disables "Block has too many lines"
BlockLength:
  Enabled: false

# Disables "Missing top-level class documentation comment"
Documentation:
  Enabled: false

# Disables "Use each_with_object instead of inject"
Style/EachWithObject:
  Enabled: false

# Disables "Prefer reduce over inject."
Style/CollectionMethods:
  Enabled: false

# Disables "%i-literals should be delimited by [ and ]."
Style/PercentLiteralDelimiters:
  Enabled: false

# Disables "Example has too many expectations"
RSpec/MultipleExpectations:
  Enabled: false

# Disables "Example has too many lines"
RSpec/ExampleLength:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Lint/MissingSuper:
  Enabled: false
